---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(arrow)

econ_id<-read_csv('junk/MMW ECONID 10.17.25.csv')



deno_calendar<-read_parquet('data/intermediate_files/denominator_by_calendar_time_period.parquet')
sort(unique(deno_calendar$deno_type))

```

## Choose calendar denominator

```{r}
#choose_deno<-deno_calendar%>%filter(deno_type %in% 'lact_basic')%>%

choose_deno<-deno_calendar%>%filter(deno_type %in% 'lact_2+')%>%
  mutate(data_source = 'calendar deno')#%>%
  #filter(calendar_time_period_type %in% 'bimonth')
```

## Wrangle econ to match calender

```{r}
wrangle_econ_id<-econ_id%>%
  select(WeekDate, `LACT>1`, `LACT=0`, `LACT=1`, `LACT>0`)%>%
  pivot_longer(cols = c('LACT>1', 'LACT=0', 'LACT=1', 'LACT>0'), 
               names_to = 'Lactation Group', 
               values_to = 'econid_count')%>%
  mutate(WeekDate = lubridate::mdy(WeekDate), 
         econid_count = parse_number(econid_count))%>%
  filter(!(is.na(WeekDate)))%>%
  mutate(data_source = 'econ id')%>%
  mutate(`Lactation Group` = case_when(
    (`Lactation Group` %in% 'LACT=0')~'Heifer', 
    (`Lactation Group` %in% 'LACT=1')~'LACT 1', 
    (`Lactation Group` %in% 'LACT>1')~'LACT 2+',
     (`Lactation Group` %in% 'LACT>0')~'LACT > 0',
    TRUE~'Unknown')
  )
```

## Visualize

Only heifers of off? and only recently??

```{r}

ggplot()+
  geom_point(data = wrangle_econ_id,
             aes(x = WeekDate, y = econid_count, color = data_source), 
             shape = 15, size = 1)+
    geom_point(data = choose_deno,
             aes(x = date_time_period_start, y = ct_animal_time_periods, color = data_source), 
             shape = 18, size = 1)+
  geom_vline(xintercept = lubridate::ymd('2025-08-15'), color = 'blue')+
  facet_wrap(`Lactation Group`~., scales = 'free')+
  theme_bw()+
  theme(legend.position = 'top')+
  scale_color_manual(values = c('calendar deno' = 'red', 'econ id' = 'black'))

#ggsave('weird.jpg')

```



```{r}
check_hfr_events<-read_parquet('data/intermediate_files/events_all_columns.parquet')%>%
  filter(lact_number == 0)%>%
  mutate(floordate_month = floor_date(date_event, unit = 'months'))%>%
  group_by(floordate_month, event_type, event)%>%
  summarize(ct_rows = sum(n()), 
            ct_animals = n_distinct(id_animal))%>%
  ungroup()
```


## Health Events

```{r}
ggplot(check_hfr_events%>%filter(event_type %in% 'health'))+
  geom_point(aes(x = floordate_month, y = ct_animals, color = event))+
  facet_wrap(event_type~.)

```

## Management Events

```{r}
ggplot(check_hfr_events%>%filter(event_type %in% 'management'))+
  geom_point(aes(x = floordate_month, y = ct_animals, color = event))+
  facet_wrap(event_type~.)

```

## Lactation Parameters

Is it true that zero heifers have been sold since July 2025?

```{r}
ggplot(check_hfr_events%>%filter(event_type %in% 'lact_parameter'))+
  geom_point(aes(x = floordate_month, y = ct_animals, color = event))+
    geom_vline(xintercept = lubridate::ymd('2025-08-01'), color = 'blue')+

  facet_wrap(event_type~.)



```

#### look for weird reasons for archive

```{r}

check<-events_formatted%>%
  group_by(floor)

```


## Repro Events

```{r}
ggplot(check_hfr_events%>%filter(event_type %in% 'repro'))+
  geom_point(aes(x = floordate_month, y = ct_animals, color = event))+
  facet_wrap(event_type~.)

```

## Unknown Events

```{r}
ggplot(check_hfr_events%>%filter(event_type %in% 'unknown'))+
  geom_point(aes(x = floordate_month, y = ct_animals, color = event))+
  facet_wrap(event_type~.)

```

## Look at event sequences

```{r}
check_hfr_events<-read_parquet('data/intermediate_files/events_all_columns.parquet')%>%
  filter(lact_number == 0)%>%
  filter(date_birth>lubridate::ymd('2024-07-01'))%>%
  mutate(floordate_birth_quarter = floor_date(date_birth, 'quarter'))%>%
  group_by(floordate_birth_quarter, id_animal)%>%
    summarize(dim_min = min(dim_event), 
              dim_max = max(dim_event))%>%
    ungroup()%>%
  filter()

ggplot(check_hfr_events)+
  geom_density(aes(x = dim_min, color = factor(floordate_birth_quarter)))+
  coord_cartesian(xlim = c(0, 150), 
                  ylim = c(0, 0.05))
#ggsave('test_first_event.jpg')
```


```{r}
list_hfrs<-sort(unique(check_hfr_events$id_animal))

sample_hfrs<-sample(list_hfrs, 10)


check_hfr_events%>%
  filter(id_animal %in% sample_hfrs)%>%
  ggplot()+
  geom_point(aes(x = dim_event, y = id_animal, color = event_type))

events<-read_parquet('data/intermediate_files/events_all_columns.parquet')

  max(events$date_event)

```

